name: Tokopedia Price Monitor

on:
yaml<br>on:<br> workflow_dispatch: {} # ← new<br> schedule:<br> - cron: '0 2 * * *'<br>
  schedule:
    # every day 09:00 WIB  (UTC+7 = 02:00 UTC)
    - cron:  '0 2 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install libs
        run: npm i tokopedia-gql csv-parser fast-csv

      - name: Run scraper
        run: node fetch-prices.js

      - name: Commit CSV
        run: |
          git config user.name  "price-bot"
          git config user.email "bot@users.noreply.github.com"
          git add today.csv
          git commit -m "daily price update $(date +'%F')" || echo "Nothing to commit"
          git push
