name: weekly-price-check

on:
  schedule:
    - cron: '0 2 * * 1'      # Monday 09:00 WIB (UTC+7)
  workflow_dispatch:         # manual run button

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json
    steps:
      - uses: actions/checkout@v4

      - name: Restore GCP creds
        run: echo "$GCP_KEY_B64" | base64 -d > "$GOOGLE_APPLICATION_CREDENTIALS"
        shell: bash

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run price checker
        run: python scripts/sku_map_v2.py
